[project]
name = "temp_api"
version = "2023.12.1"
description = "Temperature API server."
requires-python = ">=3.11"

dependencies = []

[project.scripts]
temp_api = "temp_api.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
follow_imports = "normal"
